name: tiktok_app_clone_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  change_app_package_name: ^1.1.0
  cloud_firestore: ^4.17.0
  firebase_auth: ^4.19.3
  firebase_core: ^2.30.1
  firebase_storage: ^11.7.3
  flutter:
    sdk: flutter
  flutter_naver_map: ^1.2.2
  get: ^4.6.6
  get_storage: ^2.1.1
  google_fonts: ^6.2.0
  image_picker: ^1.1.0
  simple_circular_progress_bar: ^1.0.2
  timeago: ^3.6.1
  url_launcher: ^6.2.6
  video_compress: ^3.1.2
  video_player: ^2.8.6
  share_plus:
  kakao_flutter_sdk_share: ^1.9.1+2 # 카카오톡 공유 API 패키지

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/



